### ISSUE TITLE
ceterms: Certification 

### ISSUE THREAD

**Issue by lfaulkner0328** [CredentialEngine/vocabularies#544] opened 2018-09-11 15:45 UTC
Through working with various partners around certifications for the retail and hospitality credentials initiative, there have been some questions about modifying/improving the definition of certification to include "revocation if not renewed" as a defining feature. 

We'd want to explore further if this is commonly accepted across the certification community, but we know that NCAA/ICE/ANSI include revocation as an element of personnel certification when accrediting credentialing bodies against the ISO/IEC 17024 and NCCA’s standard. When you visit the website of certification bodies, you will see that many have a section on revocation or reference the ISO/IEC 17024 standard. 

This post by Cynthia Woodley of Professional Testing was also referenced (as someone that is well respected in the certification and licensure community): https://www.proftesting.com/blog/2015/10/21/20151021what-is-certification/ 
In this post, she states: "certification belongs to the certifying body and can be taken away from the person if the person ceases competent performance, or for a host of other reasons (violation of code of ethics, failure to maintain certification requirements, failure to recertify, etc.)" 

Examples of certifying bodies that clearly spell out revocation in their code of ethics:
CompTIA: https://certification.comptia.org/testing/test-policies/continuing-education-policies/candidate-code-of-ethics
Page 34 of PMI's certification handbook: https://www.pmi.org/-/media/pmi/documents/public/pdf/certifications/project-management-professional-handbook.pdf 

I wanted to relay that this specific definition change was proposed for consideration: _Time-limited, renewable credential awarded by an authoritative body to an individual for demonstrating the designated knowledge, skills and abilities (competencies) to perform a specific occupation, specialty or skill and can be revoked if not renewed, for a violation of a code of ethics (if applicable) or proven incompetence after due process._

Wanted to share this, I'm sure more research will be needed to confirm the adoption of revocation as a part of the definition.

**Comment by siuc-nate** [comment] 2018-09-11 15:56
It's worth considering.  However, we do want to keep the definitions fairly broad and rely on data published to define individual credentials more closely.  

Of particular note here would be [Revocation Profile](http://credreg.net/ctdl/terms/RevocationProfile), which specifically exists to cover all of the details of things someone can do (or fail to do) that result in having a credential revoked, and [Renewal Profile](http://credreg.net/ctdl/terms/RenewalProfile), which covers the conditions (via ConditionProfile) one must meet in order to renew a credential.  

Between these two profiles, we intend to capture anything that must be done (or avoided) in order to "keep" a credential.  Any credential that has such requirements should be published with data in one or both of these profiles, and anything published without such data will be interpreted as not having such requirements - that enables us to cover certifications that do or don't strictly meet the definition you propose.  

It also means that if we keep our current definition, we can still cover the cases where such certifications do have stricter requirements by ensuring that the relevant data is published via one or both of those profiles.

That's my two cents anyway.

**Comment by stuartasutton** [comment] 2018-09-11 16:07
I agree with Nate above; however, if there is strong feeling here that this needs to be present, I'd suggest that it be included in a comment accompanying the definition:

>**DEFINITION:** Time-limited, renewable credential awarded by an authoritative body to an individual for demonstrating the designated knowledge, skills and abilities (competencies) to perform a specific occupation, specialty or skill. 
>
>**COMMENT:** Certificates can be revoked if not renewed, for a violation of a code of ethics (if applicable) or proven incompetence after due process. Description of revocation criteria for a specific Certification should be defined using [Revocation Profile](http://credreg.net/ctdl/terms/RevocationProfile).

**Comment by lfaulkner0328** [comment] 2018-09-11 16:18
I think that comment would be helpful to include as there is a strong feeling from the folks that I've been speaking with about revocation being a key component. 

Our outreach and engagement with certification bodies will include an emphasis on including properties like renewal and revocation, but I think having it more front and center would really help those who aren't sure if they have a certificate or a certification be able to make a more informed decision that aligns with how the community is thinking about differentiating the two.

**Comment by lfaulkner0328** [comment] 2018-09-11 16:58
Seems like the comment beneath the definition would be sufficient.

**Comment by lfaulkner0328** [comment] 2018-09-12 14:10
What would be the next steps for formally adding this comment to the definition?

**Comment by stuartasutton** [comment] 2018-09-12 17:48
After discussion is complete, it needs to be scheduled for the next available release. The update will be in pending and go out to the TAG and others for review 2 weeks prior to finalization (i.e., off pending).

**Comment by lfaulkner0328** [comment] 2018-09-12 18:30
We need to make a small but important edit to the comment @stuartasutton:
COMMENT: *Certifications* can be revoked if not renewed, for a violation of a code of ethics (if applicable) or proven incompetence after due process. Description of revocation criteria for a specific Certification should be defined using Revocation Profile.

That previously said "certificate" instead of "certification"

**Comment by siuc-nate** [comment] 2018-09-13 21:40
Action to be taken:

**Add:**
>**Subject:** ceterms:Certification
>**Predicate:** dct:description
>**Object:** Certifications can typically be revoked if not renewed, for a violation of a code of ethics (if applicable) or proven incompetence after due process. Description of revocation criteria for a specific Certification should be defined using Revocation Profile.

Any objections?

**Comment by lfaulkner0328** [comment] 2018-09-13 21:53
Can you share your thinking on adding the word "typically"? 

Does this still mean that the addition is going to be as a comment?

**Comment by siuc-nate** [comment] 2018-09-13 21:55
Yes, the change is to add a comment.

As for "typically", I am okay with leaving it out - but that means we're saying that _all_ certifications can be revoked if not renewed (etc). - and if this is true, then there's no problem removing "typically".  I am just weary of describing things too strictly, as that has bitten us before.

**Comment by stuartasutton** [comment] 2018-09-14 02:07
I think "typically" should be included for the following reason. If a distinguishing characteristic of a   certification is that it is valid for a specific period of time and then needs to be renewed for the person to remain certified, then there is no need for a revocation action since validity ends as a matter of law at the end of the prescribed timeframe. That does not mean that there isn't a custom of issuing a revocation. But why would there be a **need** to revoke if the validity of the certification ceased at the close of the prescribed period? So, leave in "typically".

**Comment by ParosGroup** [comment] 2018-09-19 21:00
I might be late to the party here, but better late than never.  
I think the issue is more, for me, about having consistency in the field about the actual definition, so as to ensure that we have things published as "certifications" that the major QA bodies who oversee them and the providers of certifications would also recognize those credentials as certifications.  If we are making changes here to have alignment with the large field, I'm not sure why we wouldn't want to drive to a common definition of certification that could/would be used by us, ANSI, ICE, GeMENA, BLS, NBER, Census, etc.  
I'd like to propose that CE co-convene a working group of experts on certifications to come up with a common definition, and get this universally resolved and consistent.

**Comment by jkitchensSIUC** [comment] 2018-09-19 21:40
@ParosGroup you're not late to the party; you're just in time... See the Credential Engine namespace policy http://credreg.net/page/namespacepolicy and CTDL Review Process PPT at the top of the CTDL History page http://credreg.net/ctdl/release.

The Credential Engine has advisory group members with expertise in this domain who provided input to the proposed definition update, including members representing ANSI.  The basis for terms related to "certification" is the International Standard ISO/IEC 17024.  The terms map to common definitions used by other organizations such as those you listed.  

Credential Engine organizes working groups around domains.  Currently, we've convened a Pathways Work Group composed of subject matter and technical experts.  Other current Credential Engine work includes development of best practices for CTDL based on types of credentials (e.g., certification).  This work may provide the opportunity your suggesting for a working group, not just to look at one definition, but a best practice for a larger set of CTDL data to describe certification.  Other team members may add their comments as well.  Thanks for posting!

**Comment by siuc-nate** [comment] 2018-10-16 15:36
Is the previously-indicated action still valid? https://github.com/CredentialEngine/vocabularies/issues/544#issuecomment-421162239

**Comment by lfaulkner0328** [comment] 2018-10-16 15:53
We are holding on any changes to this definition until we involve a few others from advisory groups in the conversation.

**Comment by stuartasutton** [comment] 2019-01-09 13:03
I prefer option 2 since it makes the person/organization distinction explicit. The labeled arrows in both options define class and subclass relationships **only** and do not carry any other notions such as "For Individuals" or "For Organizations" (i.e., unlike arrows representing properties).

**Comment by jkitchensSIUC** [comment] 2019-01-09 13:10
@stuartasutton when I posted the diagrams initially, I had to rename them and numbered the options.  Take a look at the update I made.  I may have messed up the intent of your reply.  I think you're referring to the updated naming and numbering, option 1.

**Comment by stuartasutton** [comment] 2019-01-09 14:41
@siuc-nate & @jkitchensSIUC:

To be a bit more explicit in my comment, switching from a hierarchy to tree structure, Option 1 actually looks like the following image where there is nothing hinting of the person/organization distinction.
![2019-01-09 core_entity_model_1](https://user-images.githubusercontent.com/2939046/50906029-0ee17b80-13d9-11e9-9e7f-96f654c95f00.png)

Option 2 looks like the following and clearly (and formally) indicates the person/organization distinction.

![2019-01-09 core_entity_model_2](https://user-images.githubusercontent.com/2939046/50906206-739cd600-13d9-11e9-952d-ba242cef43a6.png)

**Comment by stuartasutton** [comment] 2019-01-09 14:53
Jeanne, our posts here this morning crossed in transit :-).  Yes, I did not notice the option numbering change :-(.

**Comment by stuartasutton** [comment] 2019-01-10 12:31
No, Jeff, it would require no changes to any data...except perhaps a search of the current Certifications to gather up those that are organizational and changing their class reference.

**Comment by jeff-grann** [comment] 2019-01-14 16:54
Ok, this is good news on the registry data and I see what you mean. 

@stuartasutton What do you think about my "certifies" suggestion? I think we'd want to have consistent QA sub-class definitions so that every QA action could result in a corresponding QA credential, right? Also, in practice should QA organizations publish both a QA action and a QA credential?

**Comment by siuc-nate** [comment] 2019-01-14 17:05
That may create ambiguity in terms of whether it refers to a ceterms:Certificate or a ceterms:Certification.

It's also possible that an Action class could simply point to the type of credential that it is an action for/about, e.g.
```
{
  "@id": "https://credentialengineregistry.org/graph/ce-thisActionRecord'sURI",
  "@type": "ceterms:CredentialingAction",
  "ceterms:instrument": "https://credentialengineregistry.org/graph/ce-theQACredentialApplied",
  "ceterms:instrumentType": "ceterms:Certification"
  "ceterms:object": "https://credentialengineregistry.org/graph/ce-orgReceivingTheQA",
  "ceterms:actingAgent": "https://credentialengineregistry.org/graph/ce-qualityAssuranceOrg"
}
```
Though one could argue that the type could also be determined by fetching the graph pointed to by `ceterms:instrument` in the above example. That would probably stick closer to the principles of linked data.

**Comment by jeff-grann** [comment] 2019-01-15 15:50
Ok, so are you saying that we do NOT need a corresponding QA action such as "certifies" for the proposed Quality Assurance Certification? I guess QAOrgs could just use the existing "approves".

**Comment by siuc-nate** [comment] 2019-01-15 21:51
Per our 1/15/2019 meeting:
- Given a successful conclusion with the certification team on January 28th, we might schedule the changes to the **definition** for the February release.

**Comment by siuc-nate** [comment] 2019-02-08 16:12
What was the conclusion with the certification team? Per the post above, I need to know whether or not to do anything with the definition for this release.

**Comment by stuartasutton** [comment] 2019-02-08 16:25
Nate, that group is meeting this AM (2019-02-08). There were 2 (good) comments on the names of the organization classes. Here's my take after the only 2 comments. (ignore the placeholder for military...they didn't see that). They will be advised this AM that changes to the credential classification model is a separate conversation from their task on refining the definition of Certification (for people).

![2019-02-08 core_entity_model](https://user-images.githubusercontent.com/2939046/52491013-f94ba700-2b7a-11e9-9fc4-b84f72ccfcbc.png)

**Comment by siuc-nate** [comment] 2019-02-08 16:59
A quick googling suggests that "Industry Certification" is also used for credentials that people (among other things) can receive.

**Comment by siuc-nate** [comment] 2019-02-08 17:18
I still don't understand why the type of entity that a credential is intended for should be encoded into the credential's class and not just made to be another property of the credential (perhaps a pseudo-vocabulary in the vein of [`ceterms:credentialType`](https://credreg.net/ctdl/terms/credentialType) where the values are existing classes - likely subclasses of ceterms:Agent), e.g.:

```
{
  "@type": "ceterms:Certification",
  "ceterms:name": "Official QA Cert",
  "ceterms:intendedRecipientType": [
    "ceterms:CredentialOrganization"
  ]
}

{
  "@type": "ceterms:Certification",
  "ceterms:name": "Welding Certification",
  "ceterms:intendedRecipientType": [
    "ceterms:Person"
  ]
}
```

This allows for future expansion (credentials awarded to products, programs, assessments, learning opportunities, etc.) without doing anything to complicate the tree of credential types.

**Comment by stuartasutton** [comment] 2019-02-08 17:23
So, people have to fill in a property every time they handle this issue instead of handing it at the classification level...which makes as much sense as repetitively using a property.

**Comment by siuc-nate** [comment] 2019-02-08 17:23
Just make it a required property.

**Comment by siuc-nate** [comment] 2019-02-08 17:24
People have to fill in a property any time they want to define any aspect of a Credential - I don't see the issue.

**Comment by stuartasutton** [comment] 2019-02-08 17:24
Ah, and that lessons the burden of repeated entry...

**Comment by siuc-nate** [comment] 2019-02-08 17:32
Also, what happens when someone wants to publish a credential that isn't strict about who or what it's awarded to - say a badge for environmental responsibility or something? **Any** case where the publisher wants to offer a credential to both people and organizations, for whatever reason - we are gating them off from being able to do so by encoding that information into the type.  Using a property (or even just leaving that property off for cases where it doesn't matter) would enable such a scenario.

**Comment by lfaulkner0328** [comment] 2019-02-08 20:50
The Certification Working Group has expressed their support of the following revised definition of "certification." 

Certification: Time-limited, revocable, renewable credential awarded by an authoritative body for demonstrating the knowledge, skills, and abilities to perform specific tasks or an occupation.

Meeting notes can be found here: https://docs.google.com/document/d/1hbEkd5oovGrTSiFVepdRLrA715W4kSPQOyNFt2Oig3I/edit

**Comment by lfaulkner0328** [comment] 2019-03-01 16:44
Has this definition revision been incorporated into the next release? I thought this was moving forward but do not see it as "pending."

**Comment by siuc-nate** [comment] 2019-03-01 17:22
Change to be made in the 3-1-2019 CTDL Release:

**Remove:**
>**URI:** ceterms:Certification
>**rdfs:comment:** Time-limited, renewable credential awarded by an authoritative body to an individual or organization for demonstrating the designated knowledge, skills, and abilities to perform a specific occupation.

**Add:**
>**URI:** ceterms:Certification
>**rdfs:comment:** Time-limited, revocable, renewable credential awarded by an authoritative body for demonstrating the knowledge, skills, and abilities to perform specific tasks or an occupation.

**Comment by siuc-nate** [comment] 2019-03-01 19:07
These changes have been made and noted in the history tracking.

**Closed by siuc-nate** 2019-03-01 19:07 UTC
