### ISSUE TITLE
Inappropriate use of CredentialAlignmentObject to identify non-framework resources

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#561] opened 2018-12-16 16:10 UTC
In https://github.com/CredentialEngine/vocabularies/issues/557#issue-386921806, @siuc-nate states:

>"We would need to retain the range of [`ceterms:CredentialAlignmentObject`](http://purl.org/ctdl/terms/CredentialAlignmentObject) in order to continue enabling references/descriptions of industries and occupations that don't exist in some external framework."

Your reference is to the use of an industry type or occupation type associated with a competency framework. The quote indicates that the industry or occupation are (frequently, always?) represented by literal  and do not belong to any defined framework. The definitions and (actual) ranges of industry type and occupation type are quite explicit:

> [`ceterms:industryType`](http://purl.org/ctdl/terms/industryType): Type of industry; **select from an existing enumeration** of such types such as the SIC, NAICS, and ISIC classifications.
>
>[`ceterms:occupationType`](http://purl.org/ctdl/terms/occupationType): Type of occupation; **select from an existing enumeration** of such types.

Also, indirectly germane:

>[`ceterms:instructionalOpportunityType`](http://purl.org/ctdl/terms/instructionalProgramType): Type of instructional program; **select from an existing enumeration** of such types.

I'll admit that the way we have documented these three properties (and likely others) indicate (at the level of the CTDL) that the properties dictate the use of [`ceterms:CredentialAlignmentObject`](http://purl.org/ctdl/terms/CredentialAlignmentObject) as range. Actually they should not. 

The term declarations should look like this:

```
    {
      "@id": "http://purl.org/ctdl/terms/instructionalProgramType",
      "@type": "rdf:Property",
      "rdfs:domain": [{"@id": "ceterms:AssessmentProfile"}, {"@id": "ceterms:LearningOpportunitytProfile"}],
      "rdfs:range": {"@id": "ceterms:InstructionalProgramClassification"}
    }
```

```
    {
      "@id": "http://purl.org/ctdl/terms/occupationType",
      "@type": "rdf:Property",
      "rdfs:domain": {"@id": "ceterms:Credential"},
      "rdfs:range": {"@id": "ceterms:OccupationClassification"}
    }
```

```
    {
      "@id": "http://purl.org/ctdl/terms/industryType",
      "@type": "rdf:Property",
      "rdfs:domain": {"@id": "ceterms:Credential"},
      "rdfs:range": {"@id": "ceterms:IndustryClassification"}
    }
```
It would then be OK add a non-normative usage note to each stating that, based on circumstances, references to nodes in these frameworks could be enabled through use of [`ceterms:CredentialAlignmentObject`]() or [`schema.org/DefinedTermSet`]() (latter preferred, but former the current mechanism of the CER).

But, to return to the immediate point, all three properties reference nodes in concept schemes, not literals.

**Comment by jkitchensSIUC** [comment] 2019-03-04 22:11
@stuartasutton @siuc-nate @cwd-mparsons is this issue completed and should it be closed?

**Comment by siuc-nate** [comment] 2019-03-04 22:18
It isn't finished, but it is arguably a duplicate of #574 (specifically https://github.com/CredentialEngine/vocabularies/issues/574#issuecomment-463426110 ).  Depending on how #574 shakes out, this may also be related to #575

**Comment by siuc-nate** [comment] 2019-04-09 19:56
Per our 4-9-2019 meeting:
Closing this issue per @stuartasutton

**Closed by siuc-nate** 2019-04-09 19:56 UTC
Labels: Error
