### ISSUE TITLE
Credit Value Proposal

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#564] opened 2019-01-04 21:18 UTC
Jillian from Indiana, is currently working on a bulk upload for Indiana University East. She has brought to our attention that some their programs are a range of credit hours. For example a program ranges from 9 - 23 credit hours. Currently you can only add the single value in this field. Jillian has also mentioned they have quite a few programs that are like this.

How should we best handle this? I am sure that if Indiana has programs like this, then there are likely others who do too.

Example: https://www.iue.edu/hss/foreign-language/cert-hispanicstudies.php

**Comment by stuartasutton** [comment] 2019-01-05 14:11
It would be good for us to see 3 or 4 examples from as many sources.  While this certainly does not sound like a fringe case, having examples from a few different sources would help guarantee that we are solving a widely applicable problem **and** in a useful way.

For credit, we currently have the following:

`creditHourType` (rdf:langString)
`creditHourValue` (xsd:float)
`creditUnitType` (ceterms:CreditUnit)
`creditUnitValue` (xsd:foat)
`creditUnitDescription` (rdf:langString)

We could add to cover ranges for both hours and units:

`creditRangeLow` (xsd:float)
`creditRangeHigh` (xsd:float)

**Note:** We need to look carefully at Schema.org for instances that might guide or cover.

**Comment by philbarker** [comment] 2019-01-07 10:54
schema.org [QuantitativeValue](https://schema.org/QuantitativeValue) covers similar ground

**Comment by stuartasutton** [comment] 2019-01-07 13:41
Yes.

**Comment by siuc-nate** [comment] 2019-01-07 23:17
Would it work better to use QuantitativeValue (or some derived class) as the range for creditHourValue and creditUnitValue?

**Comment by siuc-nate** [comment] 2019-01-15 22:16
Per our 1/15/2019 meeting:
- We moved this to the next release so we have more time to review it, given its potential impact on data that has already been published and systems that are already implementing these properties.

**Comment by stuartasutton** [comment] 2019-01-19 17:43
Michael reports that there are 104 learning opportunity profiles and 1,523 condition profiles with credit unit/hour data. 

While we'd need to discuss the level of disruption, any solution should keep as simple as possible which, for me, would likely be: (1) picking up directly on schema.org/QuantitativeValue (no derivative, please, and no tailoring to the credit context only); and (2) a single new property `credit`, `creditValue`:

```
{
  "credit": {
         "@type": "QuantitiveValue", 
         "value":  25,     
         "minValue": ...,
         "maxValue": ...,
         "unitText": "Credit Hour",
         "description": "Blah, blah, blah..."
    }
}
```

**Comment by siuc-nate** [comment] 2019-03-05 22:37
I'd prefer `creditValue` over `credit`, or maybe `hasCredit` is a bit more neutral?

Regardless, this will also impact the benchmark policy discussions, as such a change will effectively replace the credit-related properties currently in use.

**Comment by stuartasutton** [comment] 2019-03-05 23:29
Sigh...

**Comment by cwd-mparsons** [comment] 2019-03-15 19:23
@stuartasutton this issue had a  milestone of today (March 15th).
Are we ready to start implementation on this change?

**Comment by stuartasutton** [comment] 2019-03-16 21:42
I've looked at this carefully and think we need to do the following:

1. Add the [`schema.org/QuantitativeValue`](https://schema.org/QuantitativeValue) to the ceterms term documentation; but
2. Use rdfs:isDefinedBy https://schema.org/ and **do not** put this class or its properties in the ceterms namespace ; 
3. Add the following schema.org properties: [`schema.org/maxValue`](https://schema.org/maxValue), [`schema.org/minValue`](https://schema.org/minValue), [`schema.org/unitText`](https://schema.org/unitText) and [`schema.org/value`](https://schema.org/value) to our ceterms term documentation;
4. Add a schema:domainIncludes [`schema.org/QuantitativeValue`](https://schema.org/QuantitativeValue) to each of the properties above in #4; 
5. Add [`schema.org/QuantitativeValue`](https://schema.org/QuantitativeValue) as schema:rangeIncludes of both [`ceterms:creditHourValue`](http://purl.org/ctdl/terms/creditHourValue) and [`ceterms:creditUnitValue`](http://purl.org/ctdl/terms/creditUnitValue);
5. **Do not** add any additional properties from [`schema.org/Thing`](https://schema.org/Thing) or from the ceterms namespace--keep this minimal and clean; and
6. Leave [`ceterms:creditHourType`](http://purl.org/ctdl/terms/creditHourValue), [`ceterms:creditUnitType`](http://purl.org/ctdl/terms/creditUnitType) and [`ceterms:creditUnitDescription`](http://purl.org/ctdl/terms/creditUnitDescription) untouched at this time.

I know that this may impact the benchmark policy discussions; but, everybody knows that changes, refinements, and updates will be ongoing and it is up to CE to develop processes that support, or at least do not hinder, such evolution.

-------------
Here are the addition/changes. Please do NOT change the definitions since we are claiming that they are defined by schema.org:

#### QuantitativeValue
```
schema:QuantitativeValue a rdf:Class ; 
   rdfs:isDefinedBy <https://schema.org/> ; 
   rdfs:label "Quantitative Value."@en-US ; 
   rdfs:comment "A point value or interval for product characteristics and other purposes."@en-US ;
   vann:usageNote "Use in CTDL to describe quantitative values such as minimum and maximum credits or credit hours etc."@en-US .
````
#### maxValue
```
schema:maxValue a rdf:Property ;
   rdfs:isDefinedBy <https://schema.org/> ;
   rdfs:label "Maximum Value"@en-US ;
   rdfs:comment "The upper value of some characteristic or property."@en-US ;
   schema:domainIncludes schema:QuantitativeValue ;
   schema:rangeIncludes xsd:float .
```
#### minValue
```
schema:minValue a rdf:Property ;
   rdfs:isDefinedBy <https://schema.org/> ;
   rdfs:label "Minimum Value"@en-US ;
   rdfs:comment "The lower value of some characteristic or property."@en-US ;
   schema:domainIncludes schema:QuantitativeValue ;
   rdfs:range xsd:float .
```
#### unitText
```
schema:unitText a rdf:Property ;
   rdfs:isDefinedBy <https://schema.org/> ;
   rdfs:label "Unit Text"@en-US ;
   rdfs:comment "A string or text indicating the unit of measurement."@en-US ;
   schema:domainIncludes schema:QuantitativeValue ;
   rdfs:range rdfs:Literal .
```
#### value
```
schema:value a rdf:Property ;
   rdfs:isDefinedBy <https://schema.org/> ;
   rdfs:label "Value"@en-US ;
   rdfs:comment "The value of the property value node."@en-US ;
   schema:domainIncludes schema:QuantitativeValue ;
   rdfs:range xsd:float .
```

**Comment by siuc-nate** [comment] 2019-03-18 14:37
Which property should have QuantitativeValue in its range?

**Comment by stuartasutton** [comment] 2019-03-18 19:58
This is the number 5 in https://github.com/CredentialEngine/vocabularies/issues/564#issuecomment-473595064:

creditHourValue
creditUnitValue

**Comment by cwd-mparsons** [comment] 2019-03-21 16:38
A little late, but out of couriousity, why are there still creditHourValue and creditUnitValue instead of just of properties like requiredCredit and educationalCredit that have QuantitativeValue  as their range? The unitText will express whether the credit is in hours or units.

Also, regarding unitText, should we have a recommended vocabulary, to minimize variations in possible values? We were already doing this for creditUnitType. Or, if retaining creditHourValue and creditUnitValue, would we then still have the controlled vocabulary for creditUnitValue?

In production, we have the following distinct values for:
**CreditHourValue**
- (blank)
- Credit Hours
- Quarter hours
- Semester
- Semester Hours
- Contact hours
- CEUs
- Hours of participation
- CEU
- semester
- Quarter credit hours

**CreditUnitValue**
- Certificate Credit
- Continuing Education Unit
- Degree Credit

**Comment by siuc-nate** [comment] 2019-03-26 16:11
Is this a correct implementation of the indiana example ( https://www.iue.edu/hss/foreign-language/cert-hispanicstudies.php )?:
```
{
	"@type": "ceterms:Certificate",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:creditHourValue": [
				{
					"@type": "schema:QuantitativeValue",
					"schema:value": 3
				},
				{
					"@type": "schema:QuantitativeValue",
					"schema:minValue": 0,
					"schema:maxValue": 14
				},
				{
					"@type": "schema:QuantitativeValue",
					"schema:value": 6
				}
			]
		}
	]
}
```

**Comment by siuc-nate** [comment] 2019-03-26 16:31
Wouldn't this be a lot simpler:
- Eliminate all 5 credit properties and start over
- Use this:
  - ceterms:creditValue
  - ceterms:creditType
  - A vocabulary to go with creditType (likely the existing vocabulary)
  - The Quantitative Value stuff above

Example:
```
{
	"@type": "ceterms:Certificate",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:creditValue": [
				{
					"@type": "schema:QuantitativeValue",
					"schema:value": 3,
					"ceterms:description": { "en": "Hispanic Culture" },
					"ceterms:creditType": {
						"@type": "ceterms:CredentialAlignmentObject",
						"ceterms:targetNode": "creditUnit:DegreeCredit",
						"ceterms:targetNodeName": { "en": "Degree Credit" }
					}
				},
				{
					"@type": "schema:QuantitativeValue",
					"schema:minValue": 0,
					"schema:maxValue": 14,
					"ceterms:description": { "en": "Spanish Language" },
					"ceterms:creditType": {
						"@type": "ceterms:CredentialAlignmentObject",
						"ceterms:targetNode": "creditUnit:DegreeCredit",
						"ceterms:targetNodeName": { "en": "Degree Credit" }
					}
				},
				{
					"@type": "schema:QuantitativeValue",
					"schema:value": 6,
					"ceterms:description": { "en": "Diversity and Culture" },
					"ceterms:creditType": {
						"@type": "ceterms:CredentialAlignmentObject",
						"ceterms:targetNode": "creditUnit:DegreeCredit",
						"ceterms:targetNodeName": { "en": "Degree Credit" }
					}
				}
			]
		}
	]
}
```

**Comment by siuc-nate** [comment] 2019-03-26 16:46
Proposed Changes:

- Deprecate creditHourType
- Deprecate creditHourValue
- Keep creditUnitType (in place of creditType in the above example)
- Deprecate creditUnitValue
- Keep creditUnitDescription (to enhance descriptions of creditType where needed)

**Comment by siuc-nate** [comment] 2019-03-26 17:00
Per our 3-26-2019 meeting:
- The proposal in my previous post is mostly complete, however there is an open question regarding whether we should:
A) Keep the existing creditUnitType property and CreditUnit vocabulary
  - And whether or not we would keep the corresponding creditUnitDescription property
B) Deprecate creditUnitType and replace it with creditType
  - And whether or not creditType would point to the CreditUnit vocabulary, or
  - Whether or not to deprecate the entire CreditUnit vocabulary and replace it with a Credit[name needed] vocabulary

I am in favor of keeping the existing property and vocabulary, so that we do not move _too_ aggressively in terms of deprecating properties and risk deprecating something we may end up wishing we had kept later on.

At **most**, I would suggest creating a new Credit[something] vocabulary and using a new creditType property to point at it, and simply mark the creditUnitType property and CreditUnit vocabulary as unstable (and/or remove the domain of the creditUnitType property), so that it is still available if and when we need it in the future.

**Comment by stuartasutton** [comment] 2019-03-26 20:00
I am for biting the bullet:

```
{
    "@type": "ceterms:Certificate",
    "ceterms:requires": [
        {
            "@type": "ceterms:ConditionProfile",
            "ceterms:creditValue": [
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 3,
                    "schema:description": { "en": "Hispanic Culture"},
                    "schema:unitText": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditType:DegreeCredit",
                        "ceterms:targetNodeName": {"en": "Degree Credit"}
                    }
                },
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:minValue": 0,
                    "schema:maxValue": 14,
                    "schema:description": {"en": "Spanish Language"},
                    "schema:unitText": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditType:DegreeCredit",
                        "ceterms:targetNodeName": {"en": "Degree Credit"}
                    }
                },
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 6,
                    "schema:description": {"en": "Diversity and Culture"},
                    "schema:unitText": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditType:DegreeCredit",
                        "ceterms:targetNodeName": {"en": "Degree Credit"}
                    }
                }
            ]
        }
    ]
}
```

1. Deprecate both `creditUnitValue` and `creditHourValue` and use [`meta:supersededBy`](http://credreg.net/meta/terms/supersededBy) referencing replacement `creditValue`;
2. Define the range of `creditValue` as `schema:QuantitativeValue`; 
3. Deprecate both `creditUnitType` and `creditHourType` and use [`meta:supersededBy`](http://credreg.net/meta/terms/supersededBy) referencing replacement `schema:unitText`;
4. Deprecate `creditUnitDescription`; and
5. Leave the concept scheme `ceterms:CreditUnit` as is.

**Comment by siuc-nate** [comment] 2019-03-27 14:58
https://schema.org/unitText appears to require text (xsd:string? Maybe rdf:langString) as a value, not a credential alignment object.

**Comment by siuc-nate** [comment] 2019-03-27 15:10
I'm also a little leery on deprecating creditUnitDescription because it enables differentiating between a description of the value and a description of the credit type itself.

In the examples above, if someone wanted to explain something about their degreeCredit separate from a description of the value itself (in other words, not mix it in with "Diversity and Culture"), how would they do it?

Actually, in trying to capture all of the data from the example, it gets even more tricky:
```
{
    "@type": "ceterms:Certificate",
    "ceterms:requires": [
        {
            "@type": "ceterms:ConditionProfile",
            "ceterms:creditValue": [
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 3,
                    "ceterms:name": {
                        "en": "Hispanic Culture"
                    },
                    "ceterms:description": {
                        "en": "Course is taught in english."
                    },
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    },
                    "ceterms:creditUnitDescription": {
                        "en": "This course's credits are required."
                    }
                },
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:minValue": 0,
                    "schema:maxValue": 14,
                    "ceterms:name": {
                        "en": "Spanish Language"
                    },
                    "ceterms:description": {
                        "en": "Requirement based on proficiency, or testing out via placement exam."
                    },
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    },
                    "ceterms:creditUnitDescription": {
                        "en": "Credit requirement depends on proficiency, or testing out via placement exam."
                    }
                },
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 6,
                    "ceterms:name": {
                        "en": "Diversity and Culture"
                    },
                    "ceterms:description": {
                        "en": "Choose two courses from the list below or other courses by approval of certificate advisors."
                    },
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    },
                    "ceterms:creditUnitDescription": {
                        "en": "These credits are elective."
                    }
                }
            ]
        }
    ]
}
```

I suspect the **correct** way to describe such complex data may be to leverage existing parts of the schema (namely learning opportunity profile, condition profile, and alternativeCondition).  I'll try to work up an example

**Comment by siuc-nate** [comment] 2019-03-27 16:04
In working through the example, it became clear to me that we are making a mistake by trying to pack too much contextual information into what is ultimately supposed to be an expression of a **value** (a single value or a range), not a **profile** of more complex information.

In my example below, I limit the use of QuantitativeValue to describing the range of required credits with no regard to the exact context of those credits, because it isn't necessary - that context is provided by the **requirements** described via condition profile and by the **learning opportunities** as blank nodes in the graph.  For brevity, I did not include all of the blank nodes that would need to exist to convey this.

```
{
    "@graph": [
        {
            "@id": "https://...",
            "@type": "ceterms:Certificate",
            "ceterms:requires": [
                {
                    "@type": "ceterms:ConditionProfile",
                    "ceterms:targetLearningOpportunity": [
                        "_:TheHispanicWorld"
                    ],
                    "ceterms:creditValue": [
                        {
                            "@type": "schema:QuantitativeValue",
                            "schema:minValue": 9,
                            "schema:maxValue": 23,
                            "ceterms:description": {
                                "en": "Credit varies depending on proficiency and placement exams."
                            },
                            "ceterms:creditType": {
                                "@type": "ceterms:CredentialAlignmentObject",
                                "ceterms:targetNode": "creditUnit:DegreeCredit",
                                "ceterms:targetNodeName": {
                                    "en": "Degree Credit"
                                }
                            }
                        }
                    ]
                },
                {
                    "@type": "ceterms:ConditionProfile",
                    "ceterms:description": {
                        "en": "Course requirements based on proficiency or testing out via placement exam"
                    },
                    "ceterms:alternativeCondition": [
                        {
                            "@type": "ceterms:ConditionProfile",
                            "ceterms:targetLearningOpportunity": [
                                "_:LoppElementarySpanishI",
                                "_:LoppElementarySpanishII",
                                "_:LoppSecondYearSpanishI",
                                "_:LoppSecondYearSpanishII"
                            ]
                        },
                        {
                            "@type": "ceterms:ConditionProfile",
                            "ceterms:targetAssessment": [
                                "_:AsmtPlacementExam"
                            ]
                        }
                    ]
                },
                {
                    "@type": "ceterms:ConditionProfile",
                    "ceterms:description": {
                        "en": "Choose two courses from the list below or other courses by approval of certificate advisors."
                    },
                    "ceterms:targetLearningOpportunity": [
                        "_:LoppSpanishCulture",
                        "_:LoppWomenInHispanicCultures",
                        "_:LoppTopicsInHispanicCultures",
                        "_:LoppCrossCultural",
                        "_:LoppIntroductionToHispanicCulture",
                        "_:LoppSpanishConversation",
                        "_:LoppIntroductionToHispanicLiterature"
                    ]
                }
            ]
        },
        {
            "@type": "ceterms:LearningOpportunityProfile",
            "@id": "_:LoppElementarySpanishI",
            "ceterms:creditValue": [
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 4,
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    }
                }
            ]
        },
        {
            "@type": "ceterms:LearningOpportunityProfile",
            "@id": "_:LoppSpanishCulture",
            "ceterms:creditValue": [
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 3,
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    }
                }
            ]
        }
    ]
}
```

I also took a similar alternative approach by attempting to use our recent pathway additions:
```
{
    "@graph": [
        {
            "@id": "https://...",
            "@type": "ceterms:Certificate",
            "ceterms:requires": [
                {
                    "@type": "ceterms:ConditionProfile",
                    "ceterms:targetPathway": [
                        "_:Pathway"
                    ],
                    "ceterms:creditValue": [
                        {
                            "@type": "schema:QuantitativeValue",
                            "schema:minValue": 9,
                            "schema:maxValue": 23,
                            "ceterms:description": {
                                "en": "Credit varies depending on proficiency and placement exams."
                            },
                            "ceterms:creditType": {
                                "@type": "ceterms:CredentialAlignmentObject",
                                "ceterms:targetNode": "creditUnit:DegreeCredit",
                                "ceterms:targetNodeName": {
                                    "en": "Degree Credit"
                                }
                            }
                        }
                    ]
                }
            ]
        },
        {
            "@type": "ceterms:Pathway",
            "@id": "_:Pathway",
            "ceterms:hasDestinationComponent": "_:FulfillmentComponent"
        },
        {
            "@type": "ceterms:BasicComponent",
            "@id": "_:FulfillmentComponent",
            "ceterms:name": {
                "en": "Conditions for earning the required credit"
            },
            "ceterms:hasChild": [
                "_:RequiredCourse",
                "_:RequiredVariableCourses",
                "_:Electives"
            ]
        },
        {
            "@type": "ceterms:CourseComponent",
            "@id": "_:RequiredCourse",
            "ceterms:sourceData": [
                "_:HispanicCulture"
            ]
        },
        {
            "@type": "ceterms:BasicComponent",
            "@id": "_:RequiredVariableCourses",
            "ceterms:sourceData": [
                "_:RequiredVariableCourseSet",
                "_:PlacementExam"
            ],
            "ceterms:hasCondition": [
                {
                    "@type": "ceterms:ComponentCondition",
                    "ceterms:requiredNumber": 1
                }
            ]
        },
        {
            "@type": "ceterms:CourseComponent",
            "@id": "_:RequiredVariableCourseSet",
            "ceterms:sourceData": [
                "_:LoppElementarySpanishI",
                "_:LoppElementarySpanishII",
                "_:LoppSecondYearSpanishI",
                "_:LoppSecondYearSpanishII"
            ],
            "ceterms:description": "Requirement based on proficiency."
        },
        {
            "@type": "ceterms:AssessmentComponent",
            "@id": "_:PlacementExam",
            "ceterms:sourceData": [
                "_:AsmtPlacementExam"
            ]
        },
        {
            "@type": "ceterms:CourseComponent",
            "@id": "_:Electives",
            "ceterms:sourceData": [
                "_:LoppSpanishCulture",
                "_:LoppWomenInHispanicCultures",
                "_:LoppTopicsInHispanicCultures",
                "_:LoppCrossCultural",
                "_:LoppIntroductionToHispanicCulture",
                "_:LoppSpanishConversation",
                "_:LoppIntroductionToHispanicLiterature"
            ],
            "ceterms:hasCondition": [
                {
                    "@type": "ceterms:ComponentCondition",
                    "ceterms:requiredNumber": 2
                }
            ]
        },
        {
            "@type": "ceterms:LearningOpportunityProfile",
            "@id": "_:LoppElementarySpanishI",
            "ceterms:creditValue": [
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 4,
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    }
                }
            ]
        },
        {
            "@type": "ceterms:LearningOpportunityProfile",
            "@id": "_:LoppSpanishCulture",
            "ceterms:creditValue": [
                {
                    "@type": "schema:QuantitativeValue",
                    "schema:value": 3,
                    "ceterms:creditType": {
                        "@type": "ceterms:CredentialAlignmentObject",
                        "ceterms:targetNode": "creditUnit:DegreeCredit",
                        "ceterms:targetNodeName": {
                            "en": "Degree Credit"
                        }
                    }
                }
            ]
        }
    ]
}
```

**I don't think we should try to pack contextual data into QuantitativeValue or we risk reinventing condition profile.**

**Comment by siuc-nate** [comment] 2019-03-27 16:39
I would also note that the problem of "how do we avoid having a dozen blank nodes to diagram this data" is probably outside the scope of this issue and may merit an issue of its own.

**Comment by siuc-nate** [comment] 2019-03-27 18:06
Per our 3-27-2019 meeting:

**URI:** ceterms:creditUnitTypeDescription
no changes

**URI:** ceterms:CreditUnit (and related concepts)
no changes

**URI:** ceterms:creditUnitValue
> **remove** vs:term_status vs:stable
> **add** vs:term_status vs:deprecated
> **add** meta:supersededBy ceterms:creditValue

**URI:** ceterms:creditHourValue
> **remove** vs:term_status vs:stable
> **add** vs:term_status vs:deprecated
> **add** meta:supersededBy ceterms:creditValue

**URI:** ceterms:creditUnitType
> **remove** vs:term_status vs:stable
> **add** vs:term_status vs:deprecated
> **add** meta:supersededBy schema:unitText

**URI:** ceterms:creditHourType
> **remove** vs:term_status vs:stable
> **add** vs:term_status vs:deprecated
> **add** meta:supersededBy schema:unitText

**URI:** ceterms:creditValue
> **add** rdfs:label "Credit Value"
> **add** rdfs:comment "A credit-related value."
> **add** schema:domainIncludes ceterms:ConditionProfile, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
> **add** schema:rangeIncludes schema:QuantitativeValue

**URI:** schema:QuantitativeValue
> **add** rdfs:label "Quantitative Value"
> **add** rdfs:isDefinedBy "https://schema.org"
> **add** rdfs:comment "A point value or interval for product characteristics and other purposes."
> **add** vann:usageNote "Use in CTDL to describe quantitative values such as minimum and maximum credits or credit hours etc."

**URI:** schema:maxValue
> **add** rdfs:label "Maximum Value"
> **add** rdfs:isDefinedBy "https://schema.org"
> **add** rdfs:comment "The upper value of some characteristic or property."
> **add** schema:domainIncludes schema:QuantitativeValue
> **add** schema:rangeIncludes xsd:float

**URI:** schema:minValue
> **add** rdfs:label "Minimum Value"
> **add** rdfs:isDefinedBy "https://schema.org"
> **add** rdfs:comment "The lower value of some characteristic or property."
> **add** schema:domainIncludes schema:QuantitativeValue
> **add** schema:rangeIncludes xsd:float

**URI:** schema:unitText
> **add** rdfs:label "Unit Text"
> **add** rdfs:isDefinedBy "https://schema.org"
> **add** rdfs:comment "A string or text indicating the unit of measurement."
> **add** schema:domainIncludes schema:QuantitativeValue
> **add** schema:rangeIncludes ceterms:CredentialAlignmentObject

**URI:** schema:value
> **add** rdfs:label "Value"
> **add** rdfs:isDefinedBy "https://schema.org"
> **add** rdfs:comment "The value of the property value node."
> **add** schema:domainIncludes schema:QuantitativeValue
> **add** schema:rangeIncludes xsd:float

**URI:** schema:description
> **add** rdfs:label "Description"
> **add** rdfs:isDefinedBy "https://schema.org"
> **add** rdfs:comment "A description of the item."
> **add** schema:domainIncludes schema:QuantitativeValue
> **add** schema:rangeIncludes rdfs:langString

**Comment by cwd-mparsons** [comment] 2019-03-28 16:42
@stuartasutton @siuc-nate The concept scheme for creditUnitType will have to be updated to include, at least the suggestions from credit hours

- semester hours, 
- quarter hours, 
- clock hours, 
- hours of participation

**Comment by stuartasutton** [comment] 2019-03-28 18:19
@jkitchensSIUC & @cwd-mparsons, since, as of tomorrow, we have this github issue in front of people regarding the property/class updates, can we reduce the possibility of confusion by moving this new  discussion about additions to the DegreeCredit vocabulary to a new github issue?

**Comment by cwd-mparsons** [comment] 2019-03-28 22:38
I created a new issue for the vocabulary: #590 

Also, a sample publish to the sandbox:
https://sandbox.credentialengineregistry.org/graph/ce-d271e466-4ebd-4042-a038-597c9ba3184e

![image](https://user-images.githubusercontent.com/26332112/55197225-e9fed800-517f-11e9-82ca-5a386085c942.png)

**Comment by siuc-nate** [comment] 2019-04-10 21:01
These changes have been made in pending CTDL and noted in the history tracking.

Note: Currently the isDefinedBy designations are left out, as I don't have a means of handling them - see #595.

**Closed by siuc-nate** 2019-04-10 21:01 UTC
